variables:
  solution: vc17/columns_ui-public.sln
  llvmMsBuildArgs: /p:PlatformToolset=ClangCL;UseLldLink=True;VcpkgAutoLink=False;WholeProgramOptimization=False;SpectreMitigation=
  vc142MsBuildArgs:
jobs:
- template: job-build.yml
  parameters:
    displayName: VS 2022 LLVM
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: Release
    msBuildArgs: ${{ variables.llvmMsBuildArgs }}
    name: vs2022_llvm
    platform: Win32
    solution: ${{ variables.solution }}
    vmImage: windows-2022
- template: job-build.yml
  parameters:
    displayName: VS 2022 v143
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: Release
        publish: true
    msBuildArgs: ${{ variables.vc142MsBuildArgs }}
    name: vs2022_v143
    platform: Win32
    solution: ${{ variables.solution }}
    vmImage: windows-2022
