name: VS 2022

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: 0 4 * * WED
  push:
    branches:
      - master

jobs:
  build:
    name: build (${{ matrix.run-code-analysis && format('{0}, code analysis', matrix.platform) || format('{0}, {1}, {2}', matrix.platform, matrix.toolset, matrix.configuration) }})
    runs-on: windows-2022
    continue-on-error: ${{ matrix.allowed-failure == true }}

    strategy:
      matrix:
        toolset: ["v143", "clang"]
        platform: ["win32"]
        configuration: ["release", "debug"]
        run-code-analysis: [false]
        include:
          - toolset: v143
            configuration: release
            enable-annotations: true
            publish-artefacts: true
          - toolset: clang
            additional-build-args: '"/p:PlatformToolset=ClangCL;LinkToolExe=link.exe"'
            allowed-failure: true
          - toolset: v143
            configuration: release
            platform: win32
            run-code-analysis: true
            allowed-failure: true
        exclude:
          - toolset: clang
            configuration: debug

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ runner.os }}-vcpkg-archives-${{ hashFiles('vcpkg.json') }}

      - name: Set up vcpkg
        run: |
          git -C C:\vcpkg fetch
          vcpkg version
          vcpkg integrate install

      - name: Set up MSBuild logger
        if: matrix.enable-annotations
        run: |
          Invoke-WebRequest -Uri https://github.com/reupen/msbuild-github-logger/releases/download/v1.0.0/Reupen.MSBuild.GitHubLogger.dll -OutFile "$Env:Temp\Reupen.MSBuild.GitHubLogger.dll"

      - name: Build
        run: |
          msbuild `
            /m `
            '/p:Platform=${{ matrix.platform }}' `
            '/p:Configuration=${{ matrix.configuration }}' `
            '/p:RunCodeAnalysis=${{ matrix.run-code-analysis }}' `
            ${{ matrix.additional-build-args }} `
            ${{ matrix.enable-annotations && '"/logger:$Env:Temp\Reupen.MSBuild.GitHubLogger.dll"' }} `
            vc17\columns_ui-public.sln

      - uses: actions/upload-artifact@v2
        if: matrix.publish-artefacts
        with:
          name: Component package (${{ matrix.configuration }})
          path: vc17\release-win32-v143\foo_ui_columns*.fb2k-component

      - uses: actions/upload-artifact@v2
        if: matrix.publish-artefacts
        with:
          name: Symbols for debugging (${{ matrix.configuration }})
          path: vc17\release-win32-v143\foo_ui_columns.pdb
